[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#ede8eb"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#fcfcfc"

# Color used for almost all text.
textColor = "#050202"